version: '3.9'
services:
  mongo:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=shop
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  product-cart-service:
    build: ./product-cart-service
    environment:
      - MONGO_URL=mongodb://admin:password@mongo:27017/shop?authSource=admin
    ports:
      - "8080:8080"
    depends_on:
      - mongo

  customer-service:
    build: ./customer-service
    environment:
      - MONGO_URL=mongodb://admin:password@mongo:27017/shop?authSource=admin
    ports:
      - "8081:8081"
    depends_on:
      - mongo

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ../client-react/dist:/usr/share/nginx/html:ro
    depends_on:
      - product-cart-service
      - customer-service

volumes:
  mongo-data:
