services:
  # --- Databases ---
  mongo-product:
    image: mongo:latest
    container_name: mongo-product
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=shop
    volumes:
      - mongo-product-data:/data/db

  mongo-customer:
    image: mongo:latest
    container_name: mongo-customer
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=customer
    volumes:
      - mongo-customer-data:/data/db

  # --- API Services (scaled manually) ---
  product-cart-service:
    build: ./product-cart-service
    environment:
      - MONGO_URL=mongodb://admin:password@mongo-product:27017/shop?authSource=admin
    depends_on:
      - mongo-product

  customer-service:
    build: ./customer-service
    environment:
      - MONGO_URL=mongodb://admin:password@mongo-customer:27017/shop?authSource=admin
    depends_on:
      - mongo-customer

  # --- NGINX Load Balancers (internal only) ---
  product-nginx-lb:
    image: nginx:alpine
    volumes:
      - ./nginx/product-lb.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - product-cart-service

  customer-nginx-lb:
    image: nginx:alpine
    volumes:
      - ./nginx/customer-lb.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - customer-service

  # --- Main NGINX Entry Point ---
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ../client-react/dist:/usr/share/nginx/html:ro
    depends_on:
      - product-cart-service
      - customer-service

volumes:
  mongo-product-data:
  mongo-customer-data:
