services:
  mongo:
    image: mongo:latest
    container_name: mongo_container
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=products
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  server:
    build: ./
    ports:
      - "8080:8080"
    environment:
      - MONGO_URL=mongodb://admin:password@mongo:27017/products?authSource=admin
    depends_on:
      - mongo

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    depends_on:
      - server
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ../client-react/dist:/usr/share/nginx/html:ro

volumes:
    mongo-data:

